version: '3'

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/login

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

